version: "3.8"

services:
  nebula:
    image: ghcr.io/infinityofspace/nebula-docker:latest
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - "./config/:/etc/nebula/config"
      - "./certs/:/etc/nebula/certs"
    command: nebula -config /etc/nebula/config/conf.yml
